spring:
  application:
    name: tflowers
  datasource:
    url: jdbc:postgresql://localhost:5432/tflowers
    password: tflowers
    username: tflowers
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
